version: '3'
services:
  sqlserver:
    container_name: Challenge.DataBase
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: Challenge2023
      ACCEPT_EULA: Y
      MSSQL_DATABASE: Challenge
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Challenge2023 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s

  sqlserver.configurator:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - ./SQL:/docker-entrypoint-initdb.d
    depends_on:
      sqlserver:
        condition: service_healthy
    command: >
      bash -c '
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P Challenge2023 -d master -i docker-entrypoint-initdb.d/init.sql;
      echo "All done!";
      '
  app:
    container_name: Challenge.Api
    depends_on: 
      - sqlserver.configurator
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_CONNECTION_STRING: $DATABASE_CONNECTION_STRING
    ports:
      - "5172:5172"
